# Generated by Django 2.2.1 on 2019-06-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sent_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
